### ISSUE TITLE
Doesn't Support SMART TVs

### ISSUE THREAD

**Issue by wahibAbdou** [magisters-org/vue-smooth-scrollbar#11]
I did build all project using this plugin but then I got surprised when I opened the website on my smart tv everything was upside down hope this gets fixed as soon as possible cause It's hard to rechange the plugin or remove it.

**Comment by magisters-org** [comment]
Which OS use your TV? OR maybe version of browser. Thx.

**Comment by wahibAbdou** [comment]
Just forget about it dude it was something else. I have a question how can I get the offset is there an event or something cause I'm using NuxtJS and I didn't find a clear path?

**Comment by magisters-org** [comment]
> Just forget about it dude it was something else. I have a question how can I get the offset is there an event or something cause I'm using NuxtJS and I didn't find a clear path to get the offset?

You can use $refs on component and access scrollbar instance (offset, etc...). For example: `this.$refs[:refName:].scrollbar.offset`
