### ISSUE TITLE
How to change the options?

### ISSUE THREAD

**Issue by forethoughtde** [magisters-org/vue-smooth-scrollbar#2]
I'd like to know how can I change the default options for vue-smooth-scrollbar? How can I change value of alwaysShowTracks to true? How can I pass value from Vue Component?

**Comment by forethoughtde** [comment]
For some reasons, even after setting alwaysShowTracks: true scrollbar is not visible.

**Comment by magisters-org** [comment]
> For some reasons, even after setting alwaysShowTracks: true scrollbar is not visible.
> 
> ```
> <smooth-scrollbar :defaults="{alwaysShowTracks: true}">
> 
> </smooth-scrollbar >
> ```

@forethoughtde try to use :options="" instead.
