### ISSUE TITLE
Accessing the scrollbar instance from parent

### ISSUE THREAD

**Issue by jessicafanfan** [magisters-org/vue-smooth-scrollbar#5]
I'm trying to make an element within the smooth-scrollbar component position fixed by doing something along the lines of this, since fixed position is not supported by smooth scrollbar:
`scrollbar.addListener(function(status) {  
  let offset = status.offset;
  fixed.style.top = offset.y + 'px';
  fixed.style.left = offset.x + 'px';
});`

How do I access the `scrollbar = SmoothScrollbar.init(.....)` instance from the SmoothScrollbar.vue file?

Thanks so much!

**Comment by magisters-org** [comment]
@jessicafanfan  you can acces scrollbar object by refs:
```
// in template
<smooth-scrollbar ref="customName">
  content...
</smooth-scrollbar>

//in methods or lifecycle hooks
const scrollbar = this.$refs.customName.scrollbar;
```
